// Pre-loaded vehicle inventory representing only the 12 verified premium vehicles
window.VEHICLES = [
  {
    id: 'mercedes-e220d',
    name: 'Mercedes E 220d',
    category: 'sedan',
    image: './media/vehicles/mercedes-e220d.jpg',
    description: 'Luxury chauffeur-driven sedan with premium interiors, smooth highway comfort, business-class travel experience, and advanced safety features.',
    pricePerDay: 9500,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    color: 'White',
    tags: ['Premium Sedan', 'Ambient Lighting', 'Soft Close'],
    travelUsage: 'Executive business transit, VIP transfers, and premium outstation trips.',
    comfortFeatures: 'Panoramic sunroof, dual-zone temperature control, premium leather reclining seats, Burmester sound.',
    suitableTravelType: 'VIP Corporate Sightseeing, Luxury Business Transit'
  },
  {
    id: 'mg-cyberster',
    name: 'MG Cyberster',
    category: 'sedan',
    image: './media/vehicles/mg-cyberster.jpg',
    description: 'Futuristic electric sports car with aggressive styling, premium cockpit, high acceleration, and luxury open-top driving experience.',
    pricePerDay: 16500,
    seats: 2,
    transmission: 'Automatic',
    fuelType: 'Electric',
    color: 'White',
    tags: ['Electric Sports', 'Scissor Doors', 'Open Top'],
    travelUsage: 'Premium city cruises, luxury leisure drives, and open-top experiential touring.',
    comfortFeatures: 'F1-inspired scissor doors, electric folding soft-top roof, premium digital dashboard, Bose audio.',
    suitableTravelType: 'Experiential Leisure, Sports Road Trips, Luxury Shoots'
  },
  {
    id: 'porsche-boxster',
    name: 'Porsche Boxster',
    category: 'sedan',
    image: './media/vehicles/porsche-boxster.jpg',
    description: 'Iconic performance roadster offering thrilling driving dynamics, premium interiors, and a high-end touring experience.',
    pricePerDay: 18000,
    seats: 2,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'Red',
    tags: ['Luxury Roadster', 'High Acceleration', 'Premium Sound'],
    travelUsage: 'High-end leisure travel, sports touring, and premium outstation weekend road trips.',
    comfortFeatures: 'Mid-engine performance chassis, premium leather bucket seats, high-fidelity acoustics, active suspension.',
    suitableTravelType: 'Elite Sports Touring, Scenic Mountain Passes, Experiential Road Trips'
  },
  {
    id: 'audi-a6',
    name: 'Audi A6',
    category: 'sedan',
    image: './media/vehicles/audi-a6.jpg',
    description: 'Elegant luxury sedan with advanced technology, spacious interiors, silent cabin comfort, and executive-class travel.',
    pricePerDay: 9000,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'White',
    tags: ['Executive Sedan', 'Silent Cabin', 'Spacious Cabin'],
    travelUsage: 'Business executive transfers, diplomatic meetings, and smooth highway family travel.',
    comfortFeatures: 'Matrix LED headlamps, virtual cockpit plus, acoustic soundproof glass, electric rear sunshade.',
    suitableTravelType: 'Executive Business Transit, Chauffeur-Driven City Tours'
  },
  {
    id: 'mercedes-s-class',
    name: 'Mercedes-Benz S-Class',
    category: 'sedan',
    image: './media/vehicles/mercedes-s-class.jpg',
    description: 'Flagship luxury sedan designed for VIP travel with unmatched comfort, ambient interiors, and elite chauffeur experience.',
    pricePerDay: 15000,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'Black',
    tags: ['Ultra Luxury VIP', 'Lounge Seating', 'Burmester Audio'],
    travelUsage: 'VIP state visits, HNWI transport, and ultimate luxury chauffeur drives.',
    comfortFeatures: 'Nappa leather lounge seats, rear passenger massage functions, active ambient lighting, executive footrests.',
    suitableTravelType: 'HNWI VIP Transportation, Luxury Weddings, Ultra-Premium Transfers'
  },
  {
    id: 'honda-city',
    name: 'Honda City',
    category: 'sedan',
    image: './media/vehicles/honda-city.jpg',
    description: 'Reliable and fuel-efficient sedan ideal for city rides, airport transfers, and comfortable family travel.',
    pricePerDay: 3500,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'Silver',
    tags: ['City Cruiser', 'Fuel Efficient', 'Comfortable Ride'],
    travelUsage: 'Daily executive transit, airport pickups, and comfortable intercity family trips.',
    comfortFeatures: 'Spacious rear legroom, automatic climate control, cruise control, multi-angle rear camera.',
    suitableTravelType: 'Family Outstation Tours, Affordable Business Travel'
  },
  {
    id: 'honda-amaze',
    name: 'Honda Amaze',
    category: 'sedan',
    image: './media/vehicles/honda-amaze.jpg',
    description: 'Practical and comfortable compact sedan suitable for local travel, daily rides, and economical trips.',
    pricePerDay: 2800,
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Petrol',
    color: 'Gold',
    tags: ['Compact Travel', 'Value Friendly', 'Easy Parking'],
    travelUsage: 'Economical city sightseeing, airport runs, and short outstation family trips.',
    comfortFeatures: 'Compact comfortable cabin, high fuel efficiency, automatic climate control, practical luggage boot.',
    suitableTravelType: 'Budget City Tours, Short Outstation Getaways'
  },
  {
    id: 'hyundai-verna',
    name: 'Hyundai Verna',
    category: 'sedan',
    image: './media/vehicles/hyundai-verna.jpg',
    description: 'Stylish premium sedan with modern interiors, smooth ride quality, and excellent long-distance comfort.',
    pricePerDay: 3200,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'Black',
    tags: ['Premium Sedan', 'Ventilated Seats', 'Quiet Ride'],
    travelUsage: 'Premium personal tours, outstation weekend getaways, and corporate sightseeing.',
    comfortFeatures: 'Ventilated front seats, ambient lighting package, smart electric sunroof, premium audio system.',
    suitableTravelType: 'Outstation Family Travel, Premium City Circuits'
  },
  // Mini Bus
  {
    id: '40-seater-bus',
    name: '40 Seater Bus',
    category: 'mini-bus',
    image: './media/vehicles/40-seater-bus.jpg',
    description: 'Spacious and comfortable bus designed for corporate tours, weddings, school trips, and large group transportation.',
    pricePerDay: 18000,
    seats: 40,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    color: 'White',
    tags: ['Corporate Travel', 'Group Seating', 'Luggage Bay'],
    travelUsage: 'Large corporate outings, destination weddings, school/college excursions, and group pilgrimage tours.',
    comfortFeatures: 'High-capacity dual blower AC, fully reclining seats, onboard dynamic TV screen, large under-belly luggage bay.',
    suitableTravelType: 'MICE Corporate Groups, Large Group Tours, Heritage Pilgrimages'
  },
  {
    id: 'toyota-innova',
    name: 'Toyota Innova',
    category: 'mini-bus',
    image: './media/vehicles/toyota-innova.jpg',
    description: 'Premium multi-passenger family travel vehicle suitable for airport transfers, family tours, and comfortable long-distance group travel.',
    pricePerDay: 5500,
    seats: 7,
    transmission: 'Manual',
    fuelType: 'Diesel',
    color: 'Maroon',
    tags: ['Family Tours', 'Spacious MPV', 'Chauffeur Driven'],
    travelUsage: 'Airport transfers, outstation family tours, small group business transit, city sightseeing tours.',
    comfortFeatures: 'Dual automatic climate control, plush sliding reclining seats, captain seats, high capacity luggage space.',
    suitableTravelType: 'Outstation Family Tours, Group Sightseeing, Corporate Transfers'
  },
  // Traveller
  {
    id: 'traveller-van',
    name: 'Traveller',
    category: 'traveller',
    image: './media/vehicles/traveller.jpg',
    description: 'Spacious tourist traveller van ideal for group tours, pilgrimage trips, long-distance journeys, and comfortable passenger transport.',
    pricePerDay: 8500,
    seats: 12,
    transmission: 'Manual',
    fuelType: 'Diesel',
    color: 'White',
    tags: ['Tourist Traveller', 'Plush Seats', 'Luggage Space'],
    travelUsage: 'Corporate sightseeing, extended family tours, pilgrimage groups, outstation group travel.',
    comfortFeatures: 'High headroom cabin, push-back reclining seats, dynamic ambient lighting, high capacity AC vents.',
    suitableTravelType: 'Group Heritage Tours, Pilgrimage Journeys, Family Getaways'
  },
  {
    id: 'toyota-fortuner',
    name: 'Toyota Fortuner',
    category: 'traveller',
    image: './media/vehicles/toyota-fortuner.jpg',
    description: 'Premium SUV designed for luxury road trips, outstation tours, hill travel, and executive family transportation.',
    pricePerDay: 7500,
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    color: 'White',
    tags: ['Premium SUV', 'All-Terrain 4x4', 'Hill Station Travel'],
    travelUsage: 'Hill station climbing, rough terrain touring, luxury family road trips, VIP corporate transit.',
    comfortFeatures: 'Premium leather upholstery, dual-zone automatic AC, active noise cancellation, heavy-duty 4x4 suspension.',
    suitableTravelType: 'Hill Station Expeditions, Rough Terrain Travel, High-End Corporate Trips'
  }
];

window.VEHICLE_GALLERIES = {
  'mercedes-e220d': ['./media/vehicles/mercedes-e220d.jpg'],
  'mg-cyberster': ['./media/vehicles/mg-cyberster.jpg'],
  'porsche-boxster': ['./media/vehicles/porsche-boxster.jpg'],
  'audi-a6': ['./media/vehicles/audi-a6.jpg'],
  'mercedes-s-class': ['./media/vehicles/mercedes-s-class.jpg'],
  'honda-city': ['./media/vehicles/honda-city.jpg'],
  'honda-amaze': ['./media/vehicles/honda-amaze.jpg'],
  'hyundai-verna': ['./media/vehicles/hyundai-verna.jpg'],
  '40-seater-bus': ['./media/vehicles/40-seater-bus.jpg'],
  'toyota-innova': ['./media/vehicles/toyota-innova.jpg'],
  'traveller-van': ['./media/vehicles/traveller.jpg'],
  'toyota-fortuner': ['./media/vehicles/toyota-fortuner.jpg']
};
