// Vehicle inventory — uses images provided by the user in media/vehicles/
window.VEHICLES = [

  // ── SEDAN ────────────────────────────────────────────────────────────────
  {
    id: 'mercedes-e220d',
    name: 'Mercedes E 220d',
    category: 'sedan',
    image: './media/vehicles/Mercedes_E_220d.jpg',
    description: 'Luxury chauffeur-driven sedan with premium interiors, smooth highway comfort, and business-class travel experience.',
    pricePerDay: 9500,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    color: 'White',
    tags: ['Premium Sedan', 'Ambient Lighting', 'Soft Close'],
    travelUsage: 'Executive business transit, VIP transfers, and premium outstation trips.',
    comfortFeatures: 'Panoramic sunroof, dual-zone climate control, premium leather seats, Burmester sound system.',
    suitableTravelType: 'VIP Corporate Sightseeing, Luxury Business Transit'
  },
  {
    id: 'mercedes-s-class',
    name: 'Mercedes-Benz S-Class',
    category: 'sedan',
    image: './media/vehicles/Mercedes_Benz_S-Class.webp',
    description: 'Flagship luxury sedan designed for VIP travel with unmatched comfort, ambient interiors, and elite chauffeur experience.',
    pricePerDay: 15000,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'Black',
    tags: ['Ultra Luxury VIP', 'Lounge Seating', 'Burmester Audio'],
    travelUsage: 'VIP state visits, HNWI transport, and ultimate luxury chauffeur drives.',
    comfortFeatures: 'Nappa leather lounge seats, rear massage functions, active ambient lighting, executive footrests.',
    suitableTravelType: 'HNWI VIP Transportation, Luxury Weddings, Ultra-Premium Transfers'
  },
  {
    id: 'audi-a6',
    name: 'Audi A6',
    category: 'sedan',
    image: './media/vehicles/Audi_A6.jpg',
    description: 'Elegant luxury sedan with advanced technology, spacious interiors, silent cabin comfort, and executive-class travel.',
    pricePerDay: 9000,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'White',
    tags: ['Executive Sedan', 'Silent Cabin', 'Spacious Interior'],
    travelUsage: 'Business executive transfers, diplomatic meetings, and smooth highway family travel.',
    comfortFeatures: 'Matrix LED headlamps, virtual cockpit plus, acoustic soundproof glass, electric rear sunshade.',
    suitableTravelType: 'Executive Business Transit, Chauffeur-Driven City Tours'
  },
  {
    id: 'mg-cyberster',
    name: 'MG Cyberster',
    category: 'sedan',
    image: './media/vehicles/MG_Cyberster.jpg',
    description: 'Futuristic electric sports car with aggressive styling, premium cockpit, high acceleration, and open-top luxury experience.',
    pricePerDay: 16500,
    seats: 2,
    transmission: 'Automatic',
    fuelType: 'Electric',
    color: 'White',
    tags: ['Electric Sports', 'Scissor Doors', 'Open Top'],
    travelUsage: 'Premium city cruises, luxury leisure drives, and open-top experiential touring.',
    comfortFeatures: 'F1-inspired scissor doors, electric folding soft-top roof, premium digital dashboard, Bose audio.',
    suitableTravelType: 'Experiential Leisure, Sports Road Trips, Luxury Shoots'
  },
  {
    id: 'porsche-boxster',
    name: 'Porsche Boxster',
    category: 'sedan',
    image: './media/vehicles/Porsche_Boxster.jpg',
    description: 'Iconic performance roadster offering thrilling driving dynamics, premium interiors, and a high-end touring experience.',
    pricePerDay: 18000,
    seats: 2,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'Silver',
    tags: ['Luxury Roadster', 'High Acceleration', 'Premium Sound'],
    travelUsage: 'High-end leisure travel, sports touring, and premium outstation weekend road trips.',
    comfortFeatures: 'Mid-engine chassis, premium leather bucket seats, high-fidelity acoustics, active suspension.',
    suitableTravelType: 'Elite Sports Touring, Scenic Mountain Passes, Experiential Road Trips'
  },
  {
    id: 'honda-city',
    name: 'Honda City',
    category: 'sedan',
    image: './media/vehicles/Honda_City.jpg',
    description: 'Reliable and fuel-efficient sedan ideal for city rides, airport transfers, and comfortable family travel.',
    pricePerDay: 3500,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'Silver',
    tags: ['City Cruiser', 'Fuel Efficient', 'Comfortable Ride'],
    travelUsage: 'Daily executive transit, airport pickups, and comfortable intercity family trips.',
    comfortFeatures: 'Spacious rear legroom, automatic climate control, cruise control, multi-angle rear camera.',
    suitableTravelType: 'Family Outstation Tours, Affordable Business Travel'
  },
  {
    id: 'honda-amaze',
    name: 'Honda Amaze',
    category: 'sedan',
    image: './media/vehicles/Honda_Amaze.jpg',
    description: 'Practical and comfortable compact sedan suitable for local travel, daily rides, and economical outstation trips.',
    pricePerDay: 2800,
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Petrol',
    color: 'Gold',
    tags: ['Compact Travel', 'Value Friendly', 'Easy Parking'],
    travelUsage: 'Economical city sightseeing, airport runs, and short outstation family trips.',
    comfortFeatures: 'Compact comfortable cabin, high fuel efficiency, automatic climate control, practical luggage boot.',
    suitableTravelType: 'Budget City Tours, Short Outstation Getaways'
  },
  {
    id: 'hyundai-verna',
    name: 'Hyundai Verna',
    category: 'sedan',
    image: './media/vehicles/Hyundai_Verna.jpg',
    description: 'Stylish premium sedan with modern interiors, smooth ride quality, and excellent long-distance comfort.',
    pricePerDay: 3200,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    color: 'Black',
    tags: ['Premium Sedan', 'Ventilated Seats', 'Quiet Ride'],
    travelUsage: 'Premium personal tours, outstation weekend getaways, and corporate sightseeing.',
    comfortFeatures: 'Ventilated front seats, ambient lighting, smart electric sunroof, premium audio system.',
    suitableTravelType: 'Outstation Family Travel, Premium City Circuits'
  },

  // ── MPV ──────────────────────────────────────────────────────────────────
  {
    id: '40-seater-bus',
    name: '40 Seater Bus',
    category: 'mpv',
    image: './media/vehicles/40-seater-bus.jpg',
    description: 'Spacious and comfortable bus designed for corporate tours, weddings, school trips, and large group transportation.',
    pricePerDay: 18000,
    seats: 40,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    color: 'White',
    tags: ['Corporate Travel', 'Group Seating', 'Luggage Bay'],
    travelUsage: 'Large corporate outings, destination weddings, school/college excursions, and group pilgrimage tours.',
    comfortFeatures: 'High-capacity dual blower AC, fully reclining seats, onboard dynamic TV screen, large under-belly luggage bay.',
    suitableTravelType: 'MICE Corporate Groups, Large Group Tours, Heritage Pilgrimages'
  },
  {
    id: 'toyota-innova',
    name: 'Toyota Innova Crysta',
    category: 'mpv',
    image: './media/vehicles/Toyota_Innova.jpg',
    description: 'Premium 7-seater MPV with captain seats, excellent highway comfort, and spacious interiors for family and group travel.',
    pricePerDay: 5500,
    seats: 7,
    transmission: 'Manual',
    fuelType: 'Diesel',
    color: 'Maroon',
    tags: ['Family MPV', 'Captain Seats', 'Spacious'],
    travelUsage: 'Airport transfers, outstation family tours, small group business transit, city sightseeing.',
    comfortFeatures: 'Dual zone climate control, push-back captain seats, large luggage space, rear privacy curtains.',
    suitableTravelType: 'Outstation Family Tours, Group Sightseeing, Corporate Transfers'
  },
  {
    id: 'toyota-fortuner',
    name: 'Toyota Fortuner',
    category: 'mpv',
    image: './media/vehicles/Toyota_Fortuner.webp',
    description: 'Premium SUV designed for luxury road trips, hill station travel, outstation tours, and executive family transportation.',
    pricePerDay: 7500,
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    color: 'White',
    tags: ['Premium SUV', 'All-Terrain 4x4', 'Hill Station'],
    travelUsage: 'Hill station travel, rough terrain touring, luxury family road trips, VIP corporate transit.',
    comfortFeatures: 'Premium leather upholstery, dual-zone AC, active noise cancellation, heavy-duty 4x4 suspension.',
    suitableTravelType: 'Hill Station Expeditions, Rough Terrain Travel, High-End Corporate Trips'
  },

  // ── TRAVELLER ────────────────────────────────────────────────────────────
  {
    id: 'force-traveller',
    name: 'Force Traveller',
    category: 'traveller',
    image: './media/vehicles/traveller.jpg',
    description: 'Spacious Force Traveller van ideal for large group tours, pilgrimage trips, and long-distance outstation travel.',
    pricePerDay: 8500,
    seats: 12,
    transmission: 'Manual',
    fuelType: 'Diesel',
    color: 'White',
    tags: ['Tourist Van', 'Plush Seats', 'Luggage Space'],
    travelUsage: 'Corporate sightseeing, extended family tours, pilgrimage groups, and outstation group travel.',
    comfortFeatures: 'High headroom cabin, push-back reclining seats, ambient lighting, high-capacity AC vents.',
    suitableTravelType: 'Group Heritage Tours, Pilgrimage Journeys, Family Getaways'
  }
];

// Gallery images per vehicle
window.VEHICLE_GALLERIES = {
  'mercedes-e220d':   ['./media/vehicles/Mercedes_E_220d.jpg'],
  'mercedes-s-class': ['./media/vehicles/Mercedes_Benz_S-Class.webp'],
  'audi-a6':          ['./media/vehicles/Audi_A6.jpg'],
  'mg-cyberster':     ['./media/vehicles/MG_Cyberster.jpg'],
  'porsche-boxster':  ['./media/vehicles/Porsche_Boxster.jpg'],
  'honda-city':       ['./media/vehicles/Honda_City.jpg'],
  'honda-amaze':      ['./media/vehicles/Honda_Amaze.jpg'],
  'hyundai-verna':    ['./media/vehicles/Hyundai_Verna.jpg'],
  '40-seater-bus':    ['./media/vehicles/40-seater-bus.jpg'],
  'toyota-innova':    ['./media/vehicles/Toyota_Innova.jpg'],
  'toyota-fortuner':  ['./media/vehicles/Toyota_Fortuner.webp'],
  'force-traveller':  ['./media/vehicles/traveller.jpg']
};
