// Pre-loaded vehicle inventory for Services page
window.VEHICLES = [
  {
    id: 'porsche-718',
    name: 'Porsche 718 (Red)',
    category: 'sports',
    image: './media/vehicles/porsche718-red.jpg',
    description: 'Mid-engine roadster with launch control and adaptive dampers.',
    pricePerDay: 18500,
    seats: 2,
    transmission: 'PDK Automatic',
    fuelType: 'Petrol',
    color: 'Guards Red',
    tags: ['Convertible', '0-100 in 4.7s', 'Premium Audio']
  },
  {
    id: 'mg-cyberster',
    name: 'MG Cyberster',
    category: 'sports',
    image: './media/vehicles/mg-cyberster.jpg',
    description: 'Electric super-roadster with scissor doors and instant torque.',
    pricePerDay: 16500,
    seats: 2,
    transmission: 'Single Speed Auto',
    fuelType: 'EV',
    color: 'Pearl White',
    tags: ['Electric', 'Scissor Doors', '360 Camera']
  },
  {
    id: 'merc-e220d',
    name: 'Mercedes Benz E220d (E-Class)',
    category: 'luxury-sedan',
    image: './media/vehicles/mercedes-e-class.jpg',
    description: 'Executive sedan with reclining rear seats and ambient lighting.',
    pricePerDay: 8500,
    seats: 5,
    transmission: '9G-TRONIC Auto',
    fuelType: 'Diesel',
    color: 'Polar White',
    tags: ['Rear Shade', 'Panoramic Roof', 'Soft Close Doors']
  },
  {
    id: 'merc-s-class',
    name: 'Mercedes Benz S-Class',
    category: 'luxury-sedan',
    image: './media/vehicles/mercedes-s-class.jpg',
    description: 'Flagship luxury with lounge seating and Burmester sound.',
    pricePerDay: 15000,
    seats: 5,
    transmission: '9G-TRONIC Auto',
    fuelType: 'Petrol',
    color: 'Obsidian Black',
    tags: ['Massage Seats', 'Rear Tablet', 'Air Suspension']
  },
  {
    id: 'audi-a6',
    name: 'Audi A6',
    category: 'luxury-sedan',
    image: './media/vehicles/audi-a6.jpg',
    description: 'Sharp business sedan with virtual cockpit and quattro poise.',
    pricePerDay: 9000,
    seats: 5,
    transmission: 'S tronic Auto',
    fuelType: 'Petrol',
    color: 'Ibis White',
    tags: ['Matrix LEDs', 'Wireless CarPlay', 'Ventilated Seats']
  },
  {
    id: 'honda-city',
    name: 'Honda City',
    category: 'budget-sedan',
    image: './media/vehicles/honda-city.jpg',
    description: 'Comfortable city cruiser with great mileage and space.',
    pricePerDay: 3500,
    seats: 5,
    transmission: 'CVT Auto',
    fuelType: 'Petrol',
    color: 'Silver',
    tags: ['Great Mileage', 'Spacious Cabin', 'Rear AC Vents']
  },
  {
    id: 'honda-amaze',
    name: 'Honda Amaze',
    category: 'budget-sedan',
    image: './media/vehicles/honda-amaze.jpg',
    description: 'Compact sedan ideal for airport drops and city errands.',
    pricePerDay: 2800,
    seats: 5,
    transmission: 'AMT',
    fuelType: 'Petrol',
    color: 'Champagne Gold',
    tags: ['Easy Parking', 'Airy Cabin', 'Value Friendly']
  },
  {
    id: 'hyundai-verna',
    name: 'Hyundai Verna',
    category: 'budget-sedan',
    image: './media/vehicles/hyundai-verna.jpg',
    description: 'Feature-rich sedan with ventilated seats and smooth ride.',
    pricePerDay: 3200,
    seats: 5,
    transmission: 'IVT Auto',
    fuelType: 'Petrol',
    color: 'Phantom Black',
    tags: ['Ventilated Seats', 'Bluelink', 'Wide Boot']
  },
  {
    id: 'toyota-fortuner',
    name: 'Toyota Fortuner',
    category: 'suv',
    image: './media/vehicles/toyota-fortuner.jpg',
    description: 'Full-size SUV with commanding presence and 4x4 capability.',
    pricePerDay: 7500,
    seats: 7,
    transmission: 'AT',
    fuelType: 'Diesel',
    color: 'Pearl White',
    tags: ['4x4', 'Captain Seats', 'Rear AC']
  },
  {
    id: 'toyota-innova',
    name: 'Toyota Innova Crysta',
    category: 'suv',
    image: './media/vehicles/toyota-innova.jpg',
    description: 'Most loved family mover with plush captain seats.',
    pricePerDay: 5500,
    seats: 7,
    transmission: 'AT',
    fuelType: 'Diesel',
    color: 'Maroon',
    tags: ['Captain Seats', 'Dual AC', 'Long Haul Ready']
  },
  {
    id: 'land-rover-defender',
    name: 'Land Rover Defender',
    category: 'suv',
    image: './media/vehicles/land-rover-defender.jpg',
    description: 'Premium adventure SUV with terrain response and luxe cabin.',
    pricePerDay: 12000,
    seats: 5,
    transmission: '8AT',
    fuelType: 'Diesel',
    color: 'Eiger Grey',
    tags: ['Terrain Response', 'Panoramic Roof', 'Meridian Audio']
  },
  {
    id: 'volvo-tourist-bus',
    name: 'Volvo Tourist Bus',
    category: 'bus',
    image: './media/vehicles/volvo-tourist-bus.jpg',
    description: '40-seater Volvo coach with pushback seats and onboard entertainment.',
    pricePerDay: 18000,
    seats: 40,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    color: 'White',
    tags: ['Pushback Seats', 'Onboard Entertainment', 'Luggage Bays']
  },
  {
    id: 'luxury-ac-bus',
    name: 'Luxury AC Tourist Bus',
    category: 'bus',
    image: './media/vehicles/luxury-ac-tourist-bus.jpg',
    description: 'Comfortable AC coach ideal for weddings, events, and group tours.',
    pricePerDay: 16000,
    seats: 32,
    transmission: 'Manual',
    fuelType: 'Diesel',
    color: 'Ivory',
    tags: ['Chiller AC', 'USB Charging', 'Curtains']
  }
];

// Optional per-vehicle gallery overrides (arrays of image URLs)
window.VEHICLE_GALLERIES = {
  'porsche-718': ['./media/vehicles/porsche718-red.jpg'],
  'mg-cyberster': ['./media/vehicles/mg-cyberster.jpg'],
  'merc-e220d': ['./media/vehicles/mercedes-e-class.jpg'],
  'merc-s-class': ['./media/vehicles/mercedes-s-class.jpg'],
  'audi-a6': ['./media/vehicles/audi-a6.jpg'],
  'honda-city': ['./media/vehicles/honda-city.jpg'],
  'honda-amaze': ['./media/vehicles/honda-amaze.jpg'],
  'hyundai-verna': ['./media/vehicles/hyundai-verna.jpg'],
  'toyota-fortuner': ['./media/vehicles/toyota-fortuner.jpg'],
  'toyota-innova': ['./media/vehicles/toyota-innova.jpg'],
  'land-rover-defender': ['./media/vehicles/land-rover-defender.jpg'],
  'volvo-tourist-bus': ['./media/vehicles/volvo-tourist-bus.jpg'],
  'luxury-ac-bus': ['./media/vehicles/luxury-ac-tourist-bus.jpg']
};
